### PR TITLE
First Commit

### PR DESCRIPTION
**Pull request by harshitptl21**

### CODE REVIEW

**Comment by ba-13** [comment]
All commands can be easily found on the internet. Documentation lies everywhere, what matters is how much of that are you willing to remember. Some basic key bindings and commands should be at your fingertips. And the writeup was meant to be comprehensive for your usage. If this seems sufficient to you, then all's good.
You can update your PR if you like till tonight, else I'll merge it.

**Comment by harshitptl21** [comment]
I think, many of us are familiar with UNIX commands and the assignment was to submit a writeup on "UNIX filesystem" and "Vim".
But, I am really thankful for your suggestion and hope for the same in the future.

**Comment by ba-13** [comment]
@harshitptl21 
Please remove the UNIX filesystem picture. I'll merge this then.

**Comment by harshitptl21** [comment]
Removed.

**Comment by ba-13** [comment]
Nicely done. Merginig

**Pull request merged**
